/* Generated by build.mjs. Keep source changes in src/ and run `npm run build`. */
(function () {
  "use strict";
const MINUTE = 60 * 1000;

function pad(value) {
  return String(value).padStart(2, '0');
}

function dateKeyFromDate(date = new Date()) {
  return `${date.getFullYear()}-${pad(date.getMonth() + 1)}-${pad(date.getDate())}`;
}

function dateFromKey(key) {
  if (typeof key !== 'string' || !/^\d{4}-\d{2}-\d{2}$/.test(key)) return null;
  const [year, month, day] = key.split('-').map(Number);
  const date = new Date(year, month - 1, day);
  if (date.getFullYear() !== year || date.getMonth() !== month - 1 || date.getDate() !== day) return null;
  date.setHours(0, 0, 0, 0);
  return date;
}

function localDateTimeIso(dateKey, time) {
  const date = dateFromKey(dateKey);
  if (!date || typeof time !== 'string' || !/^\d{2}:\d{2}$/.test(time)) return null;
  const [hours, minutes] = time.split(':').map(Number);
  if (hours > 23 || minutes > 59) return null;
  date.setHours(hours, minutes, 0, 0);
  return date.toISOString();
}

function getWeekRange(date = new Date()) {
  const start = new Date(date);
  start.setHours(0, 0, 0, 0);
  const daysFromMonday = (start.getDay() + 6) % 7;
  start.setDate(start.getDate() - daysFromMonday);
  const end = new Date(start);
  end.setDate(end.getDate() + 6);
  return { start, end };
}

function getWeekRangeFromKey(key) {
  const date = dateFromKey(key);
  return date ? getWeekRange(date) : getWeekRange();
}

function getDateKeysInRange(start, end) {
  const keys = [];
  const cursor = new Date(start);
  cursor.setHours(0, 0, 0, 0);
  const last = new Date(end);
  last.setHours(0, 0, 0, 0);
  while (cursor <= last) {
    keys.push(dateKeyFromDate(cursor));
    cursor.setDate(cursor.getDate() + 1);
  }
  return keys;
}

function formatWeekLabel(start, end, locale = undefined) {
  const options = { month: 'short', day: 'numeric' };
  const startText = start.toLocaleDateString(locale, options);
  const endText = end.toLocaleDateString(locale, { ...options, year: 'numeric' });
  return `${startText} – ${endText}`;
}

function formatDate(dateKey, locale = undefined) {
  const date = dateFromKey(dateKey);
  return date ? date.toLocaleDateString(locale, { month: 'short', day: 'numeric' }) : dateKey;
}

function formatDayName(dateKey, locale = undefined) {
  const date = dateFromKey(dateKey);
  return date ? date.toLocaleDateString(locale, { weekday: 'long' }) : '';
}

function formatDuration(totalMinutes, { compact = false } = {}) {
  const minutes = Math.max(0, Math.round(Number(totalMinutes) || 0));
  const hours = Math.floor(minutes / 60);
  const remainder = minutes % 60;
  if (compact) return `${hours}h ${pad(remainder)}m`;
  return `${hours} h ${pad(remainder)} m`;
}

function formatSignedBalance(minutes) {
  const rounded = Math.round(Number(minutes) || 0);
  if (rounded === 0) return 'On target';
  return rounded > 0 ? `${formatDuration(rounded)} over` : `${formatDuration(Math.abs(rounded))} under`;
}

function formatTime(dateOrIso, locale = undefined) {
  const date = dateOrIso instanceof Date ? dateOrIso : new Date(dateOrIso);
  if (Number.isNaN(date.getTime())) return '—';
  return date.toLocaleTimeString(locale, { hour: '2-digit', minute: '2-digit' });
}

function entryDurationMinutes(entry) {
  if (Number.isFinite(entry?.durationMinutes)) return Math.max(0, Math.round(entry.durationMinutes));
  if (entry?.start && entry?.end) return Math.max(0, Math.round((new Date(entry.end) - new Date(entry.start)) / MINUTE));
  return 0;
}

function overlapMinutes(start, end, rangeStart, rangeEnd) {
  const from = Math.max(start.getTime(), rangeStart.getTime());
  const to = Math.min(end.getTime(), rangeEnd.getTime());
  return to > from ? Math.floor((to - from) / MINUTE) : 0;
}

function activeTimerMinutesForDate(activeTimer, dateKey, now = new Date()) {
  if (!activeTimer?.startedAt || !dateFromKey(dateKey)) return 0;
  const startedAt = new Date(activeTimer.startedAt);
  const current = now instanceof Date ? now : new Date(now);
  if (Number.isNaN(startedAt.getTime()) || Number.isNaN(current.getTime())) return 0;
  const dayStart = dateFromKey(dateKey);
  const dayEnd = new Date(dayStart);
  dayEnd.setDate(dayEnd.getDate() + 1);
  return overlapMinutes(startedAt, current, dayStart, dayEnd);
}

function entriesForDate(entries, dateKey) {
  return entries.filter((entry) => entry.date === dateKey).sort((a, b) => {
    const aTime = a.start ? new Date(a.start).getTime() : Number.POSITIVE_INFINITY;
    const bTime = b.start ? new Date(b.start).getTime() : Number.POSITIVE_INFINITY;
    return aTime - bTime;
  });
}

function dailyWorkedMinutes(entries, activeTimer, dateKey, now = new Date()) {
  const completed = entriesForDate(entries, dateKey).reduce((sum, entry) => sum + (entry.source === 'vacation' ? 0 : entryDurationMinutes(entry)), 0);
  return completed + activeTimerMinutesForDate(activeTimer, dateKey, now);
}

function weeklyWorkedMinutes(entries, activeTimer, start, end, now = new Date()) {
  const startTime = start.getTime();
  const endOfWeek = new Date(end);
  endOfWeek.setDate(endOfWeek.getDate() + 1);
  const endTime = endOfWeek.getTime();
  const completed = entries.reduce((sum, entry) => {
    const date = dateFromKey(entry.date);
    return date && date >= start && date <= end && entry.source !== 'vacation' ? sum + entryDurationMinutes(entry) : sum;
  }, 0);
  const timerStart = activeTimer?.startedAt ? new Date(activeTimer.startedAt).getTime() : NaN;
  const timerEnd = now instanceof Date ? now.getTime() : new Date(now).getTime();
  const active = Number.isFinite(timerStart) ? Math.max(0, Math.floor((Math.min(timerEnd, endTime) - Math.max(timerStart, startTime)) / MINUTE)) : 0;
  return completed + active;
}

function configuredDailyTargetMinutes(settings, dateKey) {
  const date = dateFromKey(dateKey);
  return date ? Number(settings?.weekdayTargetMinutes?.[date.getDay()] || 0) : 0;
}

function vacationMinutesForDate(entries, dateKey) {
  return entries.filter((entry) => entry.date === dateKey && entry.source === 'vacation')
    .reduce((sum, entry) => sum + entryDurationMinutes(entry), 0);
}

function dailyTargetMinutes(settings, dateKey, entries = []) {
  return Math.max(0, configuredDailyTargetMinutes(settings, dateKey) - vacationMinutesForDate(entries, dateKey));
}

function weeklyTargetMinutes(settings, entries = [], start = null, end = null) {
  const vacationMinutes = entries.reduce((sum, entry) => {
    const date = dateFromKey(entry.date);
    return entry.source === 'vacation' && date && (!start || date >= start) && (!end || date <= end)
      ? sum + entryDurationMinutes(entry) : sum;
  }, 0);
  return Math.max(0, Array.from({ length: 7 }, (_, day) => Number(settings?.weekdayTargetMinutes?.[day] || 0))
    .reduce((total, target) => total + target, 0) - vacationMinutes);
}

const TIME_CONSTANTS = { MINUTE };

const STORAGE_KEY = 'workclock.data.v1';
const CURRENT_VERSION = 1;

const DEFAULT_SETTINGS = Object.freeze({
  weekdayTargetMinutes: Object.freeze({ 0: 0, 1: 480, 2: 480, 3: 480, 4: 480, 5: 480, 6: 0 }),
  weekStartsOn: 1,
});

function createDefaultState() {
  return {
    version: CURRENT_VERSION,
    settings: {
      weekdayTargetMinutes: { ...DEFAULT_SETTINGS.weekdayTargetMinutes },
      weekStartsOn: DEFAULT_SETTINGS.weekStartsOn,
    },
    entries: [],
    activeTimer: null,
  };
}

function clone(value) {
  return typeof structuredClone === 'function' ? structuredClone(value) : JSON.parse(JSON.stringify(value));
}

function isIsoString(value) {
  return typeof value === 'string' && Number.isFinite(new Date(value).getTime());
}

function isEntry(value) {
  if (!value || typeof value !== 'object') return false;
  if (typeof value.id !== 'string' || !value.id || !dateFromKey(value.date)) return false;
  if (!['manual', 'timer', 'vacation'].includes(value.source)) return false;
  if (typeof value.note !== 'string' || value.note.length > 120) return false;
  if (!Number.isInteger(value.durationMinutes) || value.durationMinutes < 0) return false;
  if (value.source === 'vacation') return value.start === null && value.end === null && value.durationMinutes > 0;
  if (value.start === null && value.end === null) return value.durationMinutes > 0;
  if (!isIsoString(value.start) || !isIsoString(value.end)) return false;
  return new Date(value.end) > new Date(value.start) && value.durationMinutes > 0;
}

function validateDocument(value) {
  if (!value || typeof value !== 'object') return { valid: false, error: 'The document is not an object.' };
  if (value.version !== CURRENT_VERSION) return { valid: false, error: `Unsupported data version. Expected version ${CURRENT_VERSION}.` };
  if (!value.settings || typeof value.settings !== 'object') return { valid: false, error: 'Settings are missing.' };
  const weekday = value.settings.weekdayTargetMinutes;
  if (!weekday || typeof weekday !== 'object') return { valid: false, error: 'Daily targets are missing.' };
  for (let day = 0; day < 7; day += 1) {
    if (!Number.isInteger(weekday[day]) || weekday[day] < 0 || weekday[day] > 1440) return { valid: false, error: 'Daily targets must be whole minutes between 0 and 1,440.' };
  }
  if (value.settings.weekStartsOn !== 1) return { valid: false, error: 'Only Monday week starts are supported.' };
  if (!Array.isArray(value.entries) || value.entries.some((entry) => !isEntry(entry))) return { valid: false, error: 'One or more entries are invalid.' };
  const ids = new Set();
  for (const entry of value.entries) {
    if (ids.has(entry.id)) return { valid: false, error: 'Entries must have unique IDs.' };
    ids.add(entry.id);
  }
  if (value.activeTimer !== null) {
    if (!value.activeTimer || typeof value.activeTimer.entryId !== 'string' || ids.has(value.activeTimer.entryId) || !isIsoString(value.activeTimer.startedAt)) {
      return { valid: false, error: 'The active timer is invalid.' };
    }
  }
  return { valid: true };
}

function createLocalStorageAdapter(storage = undefined) {
  let backend = storage;
  let available = true;
  if (backend === undefined) {
    try { backend = globalThis.localStorage; } catch { backend = null; }
  }
  if (!backend) available = false;
  return {
    get available() { return available; },
    read() {
      if (!available) return null;
      try { return backend.getItem(STORAGE_KEY); } catch { available = false; return null; }
    },
    write(value) {
      if (!available) throw new Error('Browser storage is unavailable.');
      try { backend.setItem(STORAGE_KEY, value); } catch (error) { available = false; throw new Error('Browser storage is unavailable or full.', { cause: error }); }
    },
  };
}

function loadState(adapter = createLocalStorageAdapter()) {
  const fallback = createDefaultState();
  const raw = adapter.read();
  if (!raw) return { state: fallback, error: adapter.available ? null : 'Browser storage is unavailable. Data will not persist after refresh.' };
  try {
    const parsed = JSON.parse(raw);
    const result = validateDocument(parsed);
    return result.valid ? { state: parsed, error: null } : { state: fallback, error: `Saved data could not be loaded: ${result.error}` };
  } catch {
    return { state: fallback, error: 'Saved data could not be loaded because it is malformed.' };
  }
}

function assertNoOverlap(entries, candidate, ignoreId = null) {
  const sameDayEntry = entries.some((entry) => entry.id !== ignoreId && entry.date === candidate.date);
  if (candidate.source === 'vacation' && sameDayEntry) throw new Error('This day already has an entry.');
  if (candidate.source !== 'vacation' && entries.some((entry) => entry.id !== ignoreId && entry.date === candidate.date && entry.source === 'vacation')) {
    throw new Error('This day is marked as vacation.');
  }
  if (!candidate.start || !candidate.end) return;
  const start = new Date(candidate.start).getTime();
  const end = new Date(candidate.end).getTime();
  const overlap = entries.some((entry) => {
    if (entry.id === ignoreId || entry.date !== candidate.date || !entry.start || !entry.end) return false;
    return start < new Date(entry.end).getTime() && end > new Date(entry.start).getTime();
  });
  if (overlap) throw new Error('This interval overlaps another entry on the same day.');
}

function createId() {
  if (globalThis.crypto?.randomUUID) return globalThis.crypto.randomUUID();
  return `entry-${Date.now()}-${Math.random().toString(16).slice(2)}`;
}

function createStateStore(adapter = createLocalStorageAdapter(), initialState = undefined) {
  let state = clone(initialState || loadState(adapter).state);
  const listeners = new Set();
  const notify = () => listeners.forEach((listener) => listener(state));
  const persist = () => { adapter.write(JSON.stringify(state)); };
  const mutate = (operation) => {
    const previous = clone(state);
    try { operation(); persist(); notify(); } catch (error) { state = previous; throw error; }
    return state;
  };
  return {
    getState: () => state,
    subscribe(listener) { listeners.add(listener); return () => listeners.delete(listener); },
    save() { persist(); notify(); },
    addEntry(input) {
      const entry = { id: input.id || createId(), date: input.date, start: input.start ?? null, end: input.end ?? null, durationMinutes: input.durationMinutes, note: input.note || '', source: input.source || 'manual' };
      if (!isEntry(entry)) throw new Error('Entry details are invalid.');
      assertNoOverlap(state.entries, entry);
      return mutate(() => state.entries.push(entry));
    },
    addVacation(date, note = '') {
      const durationMinutes = configuredDailyTargetMinutes(state.settings, date);
      if (!durationMinutes) throw new Error('Vacation can only be added on a day with a daily target.');
      const entry = { id: createId(), date, start: null, end: null, durationMinutes, note: note || '', source: 'vacation' };
      if (!isEntry(entry)) throw new Error('Vacation details are invalid.');
      assertNoOverlap(state.entries, entry);
      return mutate(() => state.entries.push(entry));
    },
    updateEntry(id, input) {
      const index = state.entries.findIndex((entry) => entry.id === id);
      if (index < 0) throw new Error('Entry no longer exists.');
      const entry = { ...state.entries[index], ...input, id };
      if (!isEntry(entry)) throw new Error('Entry details are invalid.');
      assertNoOverlap(state.entries, entry, id);
      return mutate(() => { state.entries[index] = entry; });
    },
    deleteEntry(id) {
      if (!state.entries.some((entry) => entry.id === id)) throw new Error('Entry no longer exists.');
      return mutate(() => { state.entries = state.entries.filter((entry) => entry.id !== id); });
    },
    startTimer(startedAt = new Date().toISOString()) {
      if (state.activeTimer) throw new Error('A timer is already running.');
      if (!isIsoString(startedAt)) throw new Error('Timer start time is invalid.');
      return mutate(() => { state.activeTimer = { entryId: createId(), startedAt }; });
    },
    stopTimer(endedAt = new Date().toISOString()) {
      if (!state.activeTimer) throw new Error('No timer is running.');
      if (!isIsoString(endedAt)) throw new Error('Timer end time is invalid.');
      const timer = state.activeTimer;
      const start = new Date(timer.startedAt);
      const end = new Date(endedAt);
      if (end <= start) throw new Error('Timer end must be after its start.');
      const firstDate = dateKeyFromDate(start);
      const secondDate = dateKeyFromDate(end);
      const newEntries = [];
      if (firstDate === secondDate) {
        newEntries.push({ id: timer.entryId, date: firstDate, start: start.toISOString(), end: end.toISOString(), durationMinutes: entryDurationMinutes({ start: start.toISOString(), end: end.toISOString() }), note: '', source: 'timer' });
      } else {
        let segmentStart = start;
        let segmentId = timer.entryId;
        while (dateKeyFromDate(segmentStart) !== secondDate) {
          const nextDay = new Date(segmentStart);
          nextDay.setHours(0, 0, 0, 0);
          nextDay.setDate(nextDay.getDate() + 1);
          const segmentEnd = nextDay < end ? nextDay : end;
          const duration = entryDurationMinutes({ start: segmentStart.toISOString(), end: segmentEnd.toISOString() });
          if (duration > 0) newEntries.push({ id: segmentId, date: dateKeyFromDate(segmentStart), start: segmentStart.toISOString(), end: segmentEnd.toISOString(), durationMinutes: duration, note: '', source: 'timer' });
          segmentStart = segmentEnd;
          segmentId = createId();
        }
        const finalDuration = entryDurationMinutes({ start: segmentStart.toISOString(), end: end.toISOString() });
        if (finalDuration > 0) newEntries.push({ id: segmentId, date: secondDate, start: segmentStart.toISOString(), end: end.toISOString(), durationMinutes: finalDuration, note: '', source: 'timer' });
      }
      for (const entry of newEntries) assertNoOverlap(state.entries, entry);
      return mutate(() => { state.entries.push(...newEntries); state.activeTimer = null; });
    },
    updateSettings(settings) {
      const next = { ...state.settings, ...settings, weekdayTargetMinutes: { ...state.settings.weekdayTargetMinutes, ...(settings.weekdayTargetMinutes || {}) } };
      const result = validateDocument({ ...state, settings: next });
      if (!result.valid) throw new Error(result.error);
      return mutate(() => { state.settings = next; });
    },
    replace(nextState) {
      const result = validateDocument(nextState);
      if (!result.valid) throw new Error(result.error);
      return mutate(() => { state = clone(nextState); });
    },
    exportJson() { return JSON.stringify(state, null, 2); },
  };
}

const adapter = createLocalStorageAdapter();
const loaded = loadState(adapter);
const store = createStateStore(adapter, loaded.state);
let selectedWeekStartKey = dateKeyFromDate(getWeekRange().start);
let timerInterval = null;

const $ = (selector) => document.querySelector(selector);
const elements = {
  headerTotal: $('#header-total'), weekHeading: $('#week-heading'), days: $('#days'),
  weeklyTotal: $('#weekly-total'), weeklyStatus: $('#weekly-status'), weeklyProgress: $('#weekly-progress'),
  weeklyTargetLabel: $('#weekly-target-label'), weeklyBalance: $('#weekly-balance'), proposedEnd: $('#proposed-end'),
  todayTimer: $('#today-timer'), storageError: $('#storage-error'), liveAnnouncer: $('#live-announcer'),
  weekCount: $('#week-count'),
  entryDialog: $('#entry-dialog'), entryForm: $('#entry-form'), entryId: $('#entry-id'), entryDate: $('#entry-date'),
  entryStart: $('#entry-start'), entryEnd: $('#entry-end'), entryDuration: $('#entry-duration'), entryNote: $('#entry-note'),
  entryDialogTitle: $('#entry-dialog-title'), formError: $('#form-error'), startField: $('#start-field'), endField: $('#end-field'),
  durationField: $('#duration-field'), vacationHelp: $('#vacation-help'), settingsForm: $('#settings-form'),
  weekdayTargets: $('#weekday-targets'), importData: $('#import-data'),
};

function escapeHtml(value) {
  return String(value ?? '').replace(/[&<>'"]/g, (character) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', "'": '&#39;', '"': '&quot;' }[character]));
}

function showError(message) {
  elements.formError.textContent = message;
  elements.formError.hidden = !message;
}

function showStorageError(message) {
  elements.storageError.textContent = message;
  elements.storageError.hidden = !message;
}

function announce(message) {
  elements.liveAnnouncer.textContent = '';
  window.setTimeout(() => { elements.liveAnnouncer.textContent = message; }, 20);
}

function setWeek(offset) {
  const range = getWeekRangeFromKey(selectedWeekStartKey);
  range.start.setDate(range.start.getDate() + offset * 7);
  selectedWeekStartKey = dateKeyFromDate(range.start);
  render();
}

function balanceClass(balance) {
  return balance > 0 ? 'is-over' : balance < 0 ? 'is-under' : 'is-neutral';
}

function render() {
  const state = store.getState();
  const now = new Date();
  const { start, end } = getWeekRangeFromKey(selectedWeekStartKey);
  const weekKeys = getDateKeysInRange(start, end).filter((key) => configuredDailyTargetMinutes(state.settings, key) > 0);
  const total = weeklyWorkedMinutes(state.entries, state.activeTimer, start, end, now);
  const target = Math.max(0, weeklyTargetMinutes(state.settings, state.entries, start, end));
  const balance = total - target;
  const progress = target > 0 ? Math.min(100, Math.round((total / target) * 100)) : 100;

  elements.weekHeading.textContent = formatWeekLabel(start, end);
  elements.headerTotal.textContent = `${formatDuration(total)} / ${formatDuration(target)}`;
  elements.weeklyTotal.textContent = formatDuration(total);
  elements.weeklyTargetLabel.textContent = `Target: ${formatDuration(target)}`;
  elements.weeklyBalance.textContent = balance === 0 ? 'On target' : `${formatDuration(Math.abs(balance))} ${balance > 0 ? 'over' : 'under'}`;
  elements.weeklyStatus.className = `status-pill ${balance > 0 ? 'status-positive' : balance < 0 ? 'status-neutral' : 'status-positive'}`;
  elements.weeklyStatus.textContent = balance > 0 ? `${formatDuration(balance)} over target` : balance < 0 ? `${formatDuration(-balance)} remaining` : 'Target reached';
  elements.weeklyProgress.setAttribute('aria-valuenow', String(progress));
  elements.weeklyProgress.querySelector('span').style.width = `${progress}%`;
  elements.proposedEnd.textContent = proposedEndText(state, now);
  renderTodayTimer(state, now);
  elements.weekCount.textContent = `${weekKeys.length} day${weekKeys.length === 1 ? '' : 's'}`;
  elements.days.innerHTML = weekKeys.map((key) => renderDay(state, key, now)).join('');
  renderSettings(state);
  showStorageError(loaded.error || (adapter.available ? '' : 'Browser storage is unavailable. Data will not persist after refresh.'));
}

function proposedEndText(state, now) {
  const todayKey = dateKeyFromDate(now);
  const vacationMinutes = vacationMinutesForDate(state.entries, todayKey);
  const target = dailyTargetMinutes(state.settings, todayKey, state.entries);
  if (target === 0) return vacationMinutes ? 'Vacation day' : 'No scheduled target';
  const worked = dailyWorkedMinutes(state.entries, state.activeTimer, todayKey, now);
  const remaining = Math.max(0, target - worked);
  if (remaining === 0) return `Target reached - ${formatDuration(worked - target)} over`;
  return `${formatTime(new Date(now.getTime() + remaining * 60 * 1000))} today`;
}

function renderTodayTimer(state, now) {
  if (!state.activeTimer) {
    elements.todayTimer.innerHTML = '<button class="button timer-button" type="button" data-action="start-timer">Start timer</button>';
    return;
  }
  elements.todayTimer.innerHTML = `<div class="today-timer-status"><span>Timer running</span><strong data-live-timer="${escapeHtml(state.activeTimer.startedAt)}">${formatElapsed(state.activeTimer.startedAt, now)}</strong></div><button class="button timer-button" type="button" data-action="stop-timer">Stop timer</button>`;
}

function renderDay(state, dateKey, now) {
  const todayKey = dateKeyFromDate(now);
  const isToday = dateKey === todayKey;
  const target = dailyTargetMinutes(state.settings, dateKey, state.entries);
  const vacationMinutes = vacationMinutesForDate(state.entries, dateKey);
  const worked = dailyWorkedMinutes(state.entries, state.activeTimer, dateKey, now);
  const balance = worked - target;
  const entries = entriesForDate(state.entries, dateKey);
  const activeMinutes = activeTimerMinutesForDate(state.activeTimer, dateKey, now);
  const hasActiveTimer = Boolean(state.activeTimer && activeMinutes >= 0 && dateKey === dateKeyFromDate(new Date(state.activeTimer.startedAt)));
  const entryMarkup = entries.map((entry) => renderEntry(entry)).join('');
  const runningMarkup = hasActiveTimer ? `<div class="entry-row running"><div class="entry-main"><span>Timer running</span><span data-live-timer="${escapeHtml(state.activeTimer.startedAt)}">${formatElapsed(state.activeTimer.startedAt, now)}</span></div><div class="entry-note">Started ${formatTime(state.activeTimer.startedAt)}</div></div>` : '';
  return `<article class="day-card ${isToday ? 'is-today' : ''}">
    <div class="day-card-header"><div><div class="day-name">${escapeHtml(formatDayName(dateKey))}</div><div class="day-date">${escapeHtml(formatDate(dateKey))}</div></div>${isToday ? '<span class="today-tag">Today</span>' : ''}</div>
    <p class="day-total">${formatDuration(worked)}</p><div class="day-target">${vacationMinutes ? `Target reduced by ${formatDuration(vacationMinutes)}` : `Target: ${target ? formatDuration(target) : 'No target'}`}</div>
    <div class="day-balance ${balanceClass(balance)}">${target ? escapeHtml(formatSignedBalance(balance)) : vacationMinutes ? 'Vacation day' : `${formatDuration(worked)} logged`}</div>
    <div class="entry-list">${runningMarkup}${entryMarkup || (!runningMarkup ? '<div class="empty-day">No entries yet</div>' : '')}</div>
    <div class="day-actions"><button class="text-button" type="button" data-action="add-entry" data-date="${dateKey}">+ Add manual entry</button><button class="text-button vacation-action" type="button" data-action="add-vacation" data-date="${dateKey}">+ Add full-day vacation</button></div>
  </article>`;
}

function renderEntry(entry) {
  const isVacation = entry.source === 'vacation';
  const timeText = isVacation ? 'Vacation' : entry.start && entry.end ? `${formatTime(entry.start)} - ${formatTime(entry.end)}` : `${formatDuration(entry.durationMinutes)} - duration only`;
  const amountText = isVacation ? `${formatDuration(entry.durationMinutes, { compact: true })} target` : formatDuration(entry.durationMinutes, { compact: true });
  return `<div class="entry-row ${isVacation ? 'vacation-entry' : ''}"><div class="entry-main"><span>${escapeHtml(timeText)}</span><span>${escapeHtml(amountText)}</span></div>${entry.note ? `<div class="entry-note" title="${escapeHtml(entry.note)}">${escapeHtml(entry.note)}</div>` : ''}<div class="entry-actions"><button class="text-button" type="button" data-action="edit-entry" data-id="${escapeHtml(entry.id)}">Edit</button><button class="text-button delete" type="button" data-action="delete-entry" data-id="${escapeHtml(entry.id)}">Delete</button></div></div>`;
}

function formatElapsed(startedAt, now = new Date()) {
  const milliseconds = Math.max(0, now - new Date(startedAt));
  const hours = Math.floor(milliseconds / 3600000);
  const minutes = Math.floor((milliseconds % 3600000) / 60000);
  const seconds = Math.floor((milliseconds % 60000) / 1000);
  return `${String(hours).padStart(2, '0')}:${String(minutes).padStart(2, '0')}:${String(seconds).padStart(2, '0')}`;
}

function renderSettings(state) {
  elements.weekdayTargets.innerHTML = [1, 2, 3, 4, 5, 6, 0].map((day) => {
    const date = new Date(2024, 0, day === 0 ? 7 : day + 1);
    const label = date.toLocaleDateString(undefined, { weekday: 'short' });
    return `<label>${label}<input name="weekday-target-${day}" type="number" min="0" max="24" step="0.25" value="${state.settings.weekdayTargetMinutes[day] / 60}" required></label>`;
  }).join('');
}

function toggleEntryMode() {
  const mode = elements.entryForm.querySelector('input[name="entry-mode"]:checked').value;
  const durationMode = mode === 'duration';
  const vacationMode = mode === 'vacation';
  elements.startField.hidden = durationMode || vacationMode;
  elements.endField.hidden = durationMode || vacationMode;
  elements.durationField.hidden = !durationMode;
  elements.vacationHelp.hidden = !vacationMode;
  elements.entryStart.required = !durationMode && !vacationMode;
  elements.entryEnd.required = !durationMode && !vacationMode;
  elements.entryDuration.required = durationMode;
  elements.entryForm.querySelector('button[type="submit"]').textContent = vacationMode ? 'Save vacation' : 'Save entry';
}

function openEntryDialog(dateKey, entryId = '', requestedMode = 'interval') {
  const entry = entryId ? store.getState().entries.find((item) => item.id === entryId) : null;
  elements.entryForm.reset();
  showError('');
  elements.entryId.value = entry?.id || '';
  elements.entryDate.value = entry?.date || dateKey;
  elements.entryNote.value = entry?.note || '';
  elements.entryDialogTitle.textContent = entry ? (entry.source === 'vacation' ? 'Edit vacation' : 'Edit entry') : requestedMode === 'vacation' ? 'Add vacation' : 'Add entry';
  if (entry?.source === 'vacation') {
    elements.entryForm.querySelector('input[value="vacation"]').checked = true;
  } else if (entry?.start && entry?.end) {
    elements.entryForm.querySelector('input[value="interval"]').checked = true;
    elements.entryStart.value = localTimeValue(entry.start);
    elements.entryEnd.value = localTimeValue(entry.end);
  } else if (entry) {
    elements.entryForm.querySelector('input[value="duration"]').checked = true;
    elements.entryDuration.value = String(entry.durationMinutes);
  } else {
    elements.entryForm.querySelector(`input[value="${requestedMode}"]`).checked = true;
  }
  toggleEntryMode();
  elements.entryDialog.showModal();
  elements.entryDate.focus();
}

function localTimeValue(iso) {
  const date = new Date(iso);
  return `${String(date.getHours()).padStart(2, '0')}:${String(date.getMinutes()).padStart(2, '0')}`;
}

function saveEntry(event) {
  event.preventDefault();
  showError('');
  const date = elements.entryDate.value;
  if (!dateFromKey(date)) return showError('Choose a valid date.');
  const mode = elements.entryForm.querySelector('input[name="entry-mode"]:checked').value;
  const input = { date, note: elements.entryNote.value.trim(), source: 'manual' };
  if (mode === 'vacation') {
    input.source = 'vacation'; input.start = null; input.end = null;
    input.durationMinutes = configuredDailyTargetMinutes(store.getState().settings, date);
    if (!input.durationMinutes) return showError('Vacation can only be added on a day with a daily target.');
  } else if (mode === 'duration') {
    const duration = Number(elements.entryDuration.value);
    if (!Number.isInteger(duration) || duration < 1) return showError('Duration must be a whole number of minutes greater than zero.');
    input.durationMinutes = duration; input.start = null; input.end = null;
  } else {
    input.start = localDateTimeIso(date, elements.entryStart.value);
    input.end = localDateTimeIso(date, elements.entryEnd.value);
    if (!input.start || !input.end) return showError('Enter both a valid start and end time.');
    if (new Date(input.end) <= new Date(input.start)) return showError('End time must be after start time. Overnight entries must be split across dates.');
    input.durationMinutes = Math.round((new Date(input.end) - new Date(input.start)) / 60000);
  }
  try {
    if (elements.entryId.value) store.updateEntry(elements.entryId.value, input);
    else if (mode === 'vacation') store.addVacation(date, input.note);
    else store.addEntry(input);
    elements.entryDialog.close();
    announce(mode === 'vacation' ? 'Vacation saved.' : 'Entry saved.');
    render();
  } catch (error) { showError(error.message); showStorageError(error.message); }
}

function handleDayAction(event) {
  const control = event.target.closest('[data-action]');
  if (!control) return;
  const action = control.dataset.action;
  try {
    if (action === 'add-entry') openEntryDialog(control.dataset.date);
    if (action === 'add-vacation') openEntryDialog(control.dataset.date, '', 'vacation');
    if (action === 'edit-entry') openEntryDialog('', control.dataset.id);
    if (action === 'delete-entry') {
      if (window.confirm('Delete this entry? This cannot be undone.')) { store.deleteEntry(control.dataset.id); announce('Entry deleted.'); render(); }
    }
    if (action === 'start-timer') {
      store.startTimer(); announce('Timer started.'); render();
    }
    if (action === 'stop-timer') {
      const timer = store.getState().activeTimer;
      if (timer && dateKeyFromDate(new Date(timer.startedAt)) !== dateKeyFromDate(new Date()) && !window.confirm('This timer crossed midnight. It will be split across the two dates. Stop it?')) return;
      store.stopTimer(); announce('Timer stopped and saved.'); render();
    }
  } catch (error) { showStorageError(error.message); }
}

async function importData(event) {
  const file = event.target.files?.[0];
  event.target.value = '';
  if (!file) return;
  try {
    const parsed = JSON.parse(await file.text());
    const result = validateDocument(parsed);
    if (!result.valid) throw new Error(result.error);
    if (!window.confirm('Replace all current WorkClock data with this backup?')) return;
    store.replace(parsed);
    announce('Backup imported.'); render();
  } catch (error) { showStorageError(`Import failed: ${error.message}`); }
}

function exportData() {
  const blob = new Blob([store.exportJson()], { type: 'application/json' });
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url; link.download = `workclock-${dateKeyFromDate(new Date())}.json`;
  document.body.appendChild(link); link.click(); link.remove(); URL.revokeObjectURL(url);
  announce('Backup exported.');
}

function saveSettings(event) {
  event.preventDefault();
  try {
    const weekdayTargetMinutes = {};
    for (const day of [0, 1, 2, 3, 4, 5, 6]) {
      const hours = Number(elements.settingsForm.querySelector(`[name="weekday-target-${day}"]`).value);
      if (!Number.isFinite(hours) || hours < 0 || hours > 24) throw new Error('Daily targets must be between 0 and 24 hours.');
      weekdayTargetMinutes[day] = Math.round(hours * 60);
    }
    store.updateSettings({ weekdayTargetMinutes });
    announce('Targets saved.'); render();
  } catch (error) { showStorageError(error.message); }
}

$('#previous-week').addEventListener('click', () => setWeek(-1));
$('#next-week').addEventListener('click', () => setWeek(1));
$('#today-week').addEventListener('click', () => { selectedWeekStartKey = dateKeyFromDate(getWeekRange().start); render(); });
elements.days.addEventListener('click', handleDayAction);
elements.todayTimer.addEventListener('click', handleDayAction);
elements.entryForm.addEventListener('submit', saveEntry);
elements.entryForm.querySelectorAll('input[name="entry-mode"]').forEach((input) => input.addEventListener('change', toggleEntryMode));
$('#close-entry').addEventListener('click', () => elements.entryDialog.close());
$('#cancel-entry').addEventListener('click', () => elements.entryDialog.close());
elements.settingsForm.addEventListener('submit', saveSettings);
$('#export-data').addEventListener('click', exportData);
elements.importData.addEventListener('change', importData);
elements.entryDialog.addEventListener('click', (event) => { if (event.target === elements.entryDialog) elements.entryDialog.close(); });

store.subscribe(() => { if (!adapter.available) showStorageError('Browser storage is unavailable or full. Changes are only in memory.'); });
timerInterval = window.setInterval(() => { if (store.getState().activeTimer) render(); }, 1000);
toggleEntryMode();
render();

}());
